import {
  FoodDonation,
  FoodRequirement,
  User,
  DonorProfile,
  NgoProfile,
  VolunteerProfile,
  DeliveryTask,
  NotificationItem,
  ImpactMetrics,
} from '@/types';

export const DEMO_USERS: User[] = [
  {
    id: 'user-donor-1',
    email: 'donor@demo.com',
    name: 'Raj Kumar',
    role: 'donor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Raj',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-ngo-1',
    email: 'ngo@demo.com',
    name: 'Priya Sharma',
    role: 'ngo',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'user-volunteer-1',
    email: 'volunteer@demo.com',
    name: 'Arjun Singh',
    role: 'volunteer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun',
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'user-admin-1',
    email: 'admin@demo.com',
    name: 'Anita Patel',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anita',
    createdAt: '2024-01-01T10:00:00Z',
  },
];

export const DEMO_DONOR_PROFILES: DonorProfile[] = [
  {
    userId: 'user-donor-1',
    organizationName: 'Grand Hyatt Restaurant',
    organizationType: 'restaurant',
    location: { lat: 28.6139, lng: 77.2090, address: 'Connaught Place, New Delhi' },
    phone: '+91-98765-43210',
    totalDonations: 47,
    totalMeals: 1240,
    totalKg: 620,
  },
  {
    userId: 'user-donor-2',
    organizationName: 'Fresh Harvest Market',
    organizationType: 'supermarket',
    location: { lat: 28.6280, lng: 77.2190, address: 'Karol Bagh, New Delhi' },
    phone: '+91-98765-11111',
    totalDonations: 38,
    totalMeals: 980,
    totalKg: 490,
  },
  {
    userId: 'user-donor-3',
    organizationName: 'Olive Tree Bakery',
    organizationType: 'bakery',
    location: { lat: 28.5921, lng: 77.2289, address: 'Lajpat Nagar, New Delhi' },
    phone: '+91-98765-22222',
    totalDonations: 62,
    totalMeals: 1860,
    totalKg: 930,
  },
  {
    userId: 'user-donor-4',
    organizationName: 'The Taj Mahal Hotel',
    organizationType: 'hotel',
    location: { lat: 28.6448, lng: 77.1074, address: 'Diplomatic Enclave, New Delhi' },
    phone: '+91-98765-33333',
    totalDonations: 25,
    totalMeals: 750,
    totalKg: 375,
  },
];

export const DEMO_NGO_PROFILES: NgoProfile[] = [
  {
    userId: 'ngo-1',
    organizationName: 'Hope Food Bank',
    location: { lat: 28.6304, lng: 77.2177, address: 'Paharganj, New Delhi' },
    phone: '+91-11-2345-6789',
    capacity: 500,
    currentLoad: 180,
    beneficiariesServed: 12450,
    acceptedCategories: ['cooked_meals', 'packaged_goods', 'fresh_produce', 'bakery'],
    requirementsActive: 3,
  },
  {
    userId: 'ngo-2',
    organizationName: 'St. Jude Shelter Home',
    location: { lat: 28.6562, lng: 77.2410, address: 'Civil Lines, New Delhi' },
    phone: '+91-11-2345-7890',
    capacity: 300,
    currentLoad: 210,
    beneficiariesServed: 8900,
    acceptedCategories: ['cooked_meals', 'bakery', 'dairy'],
    requirementsActive: 2,
  },
  {
    userId: 'ngo-3',
    organizationName: 'City Community Kitchen',
    location: { lat: 28.5706, lng: 77.3210, address: 'Noida Sector 18, UP' },
    phone: '+91-120-456-7890',
    capacity: 800,
    currentLoad: 320,
    beneficiariesServed: 21000,
    acceptedCategories: ['cooked_meals', 'fresh_produce', 'packaged_goods', 'dairy', 'beverages'],
    requirementsActive: 4,
  },
  {
    userId: 'ngo-4',
    organizationName: 'Child Care Trust',
    location: { lat: 28.5355, lng: 77.3910, address: 'Greater Noida, UP' },
    phone: '+91-120-567-8901',
    capacity: 200,
    currentLoad: 85,
    beneficiariesServed: 5600,
    acceptedCategories: ['fresh_produce', 'dairy', 'packaged_goods', 'snacks'],
    requirementsActive: 1,
  },
  {
    userId: 'ngo-5',
    organizationName: 'Grace Meal Program',
    location: { lat: 28.5245, lng: 77.1855, address: 'Vasant Kunj, New Delhi' },
    phone: '+91-11-3456-7890',
    capacity: 400,
    currentLoad: 160,
    beneficiariesServed: 9800,
    acceptedCategories: ['cooked_meals', 'bakery', 'fresh_produce', 'packaged_goods'],
    requirementsActive: 2,
  },
];

export const DEMO_VOLUNTEER_PROFILES: VolunteerProfile[] = [
  {
    userId: 'user-volunteer-1',
    name: 'Arjun Singh',
    location: { lat: 28.6200, lng: 77.2100, address: 'Rajouri Garden, New Delhi' },
    phone: '+91-99887-12345',
    vehicleType: 'van',
    deliveriesCompleted: 89,
    rating: 4.8,
    isAvailable: true,
  },
  {
    userId: 'volunteer-2',
    name: 'Meera Kapoor',
    location: { lat: 28.6400, lng: 77.2300, address: 'Rohini, New Delhi' },
    phone: '+91-99887-23456',
    vehicleType: 'car',
    deliveriesCompleted: 54,
    rating: 4.9,
    isAvailable: true,
  },
  {
    userId: 'volunteer-3',
    name: 'Rohit Verma',
    location: { lat: 28.5800, lng: 77.2500, address: 'Saket, New Delhi' },
    phone: '+91-99887-34567',
    vehicleType: 'bike',
    deliveriesCompleted: 121,
    rating: 4.7,
    isAvailable: false,
  },
  {
    userId: 'volunteer-4',
    name: 'Sunita Devi',
    location: { lat: 28.6100, lng: 77.3500, address: 'Mayur Vihar, New Delhi' },
    phone: '+91-99887-45678',
    vehicleType: 'car',
    deliveriesCompleted: 33,
    rating: 4.6,
    isAvailable: true,
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();

export const DEMO_DONATIONS: FoodDonation[] = [
  {
    id: 'donation-1',
    donorId: 'user-donor-1',
    donorName: 'Raj Kumar',
    donorOrgName: 'Grand Hyatt Restaurant',
    foodName: 'Dal Makhani & Rice Combo',
    category: 'cooked_meals',
    quantity: 80,
    quantityKg: 40,
    preparationTime: hoursAgo(2),
    expiryTime: hoursFromNow(4),
    storageCondition: 'heated',
    pickupAddress: 'Connaught Place, New Delhi',
    location: { lat: 28.6139, lng: 77.2090, address: 'Connaught Place, New Delhi' },
    notes: 'Freshly prepared dal makhani with steamed rice. Packed in hygienic containers.',
    status: 'pending',
    urgencyLevel: 'critical',
    aiAnalysis: {
      predictedCategory: 'cooked_meals',
      urgencyLevel: 'critical',
      estimatedShelfLifeHours: 4,
      storageRecommendation: 'Keep heated above 60°C or refrigerate immediately. Consume within 4 hours.',
      confidenceScore: 94,
      explanation: 'Cooked lentil curry with rice - high moisture content and protein makes this high-risk. Prepared 2 hours ago, should be consumed within 4 hours at ambient temperature.',
      safetyWarnings: ['Do not leave at room temperature for more than 2 hours', 'Reheat to 75°C before serving'],
    },
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'donation-2',
    donorId: 'user-donor-3',
    donorName: 'Sunita Mehta',
    donorOrgName: 'Olive Tree Bakery',
    foodName: 'Assorted Croissants & Sourdough',
    category: 'bakery',
    quantity: 120,
    quantityKg: 36,
    preparationTime: hoursAgo(6),
    expiryTime: hoursFromNow(18),
    storageCondition: 'ambient',
    pickupAddress: 'Lajpat Nagar, New Delhi',
    location: { lat: 28.5921, lng: 77.2289, address: 'Lajpat Nagar, New Delhi' },
    notes: 'Fresh baked this morning. Variety pack including plain, chocolate, and almond croissants plus artisan sourdough.',
    status: 'matched',
    urgencyLevel: 'medium',
    aiAnalysis: {
      predictedCategory: 'bakery',
      urgencyLevel: 'medium',
      estimatedShelfLifeHours: 18,
      storageRecommendation: 'Store in a cool, dry place. Avoid plastic bags to maintain crispness.',
      confidenceScore: 91,
      explanation: 'Bakery items have good shelf stability at ambient temperature for 18-24 hours from baking time.',
      safetyWarnings: ['Check for mold before distribution'],
    },
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'donation-3',
    donorId: 'user-donor-2',
    donorName: 'Vikram Nair',
    donorOrgName: 'Fresh Harvest Market',
    foodName: 'Mixed Organic Vegetables',
    category: 'fresh_produce',
    quantity: 60,
    quantityKg: 45,
    preparationTime: hoursAgo(1),
    expiryTime: hoursFromNow(36),
    storageCondition: 'refrigerated',
    pickupAddress: 'Karol Bagh, New Delhi',
    location: { lat: 28.6280, lng: 77.2190, address: 'Karol Bagh, New Delhi' },
    notes: 'Carrots, spinach, tomatoes, and potatoes. Near best-before date but fully edible.',
    status: 'pending',
    urgencyLevel: 'low',
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'donation-4',
    donorId: 'user-donor-4',
    donorName: 'Nisha Agarwal',
    donorOrgName: 'The Taj Mahal Hotel',
    foodName: 'Chicken Biryani & Raita',
    category: 'cooked_meals',
    quantity: 50,
    quantityKg: 25,
    preparationTime: hoursAgo(1),
    expiryTime: hoursFromNow(5),
    storageCondition: 'heated',
    pickupAddress: 'Diplomatic Enclave, New Delhi',
    location: { lat: 28.6448, lng: 77.1074, address: 'Diplomatic Enclave, New Delhi' },
    notes: 'Dum biryani from today\'s banquet event. Premium quality.',
    status: 'pending',
    urgencyLevel: 'high',
    aiAnalysis: {
      predictedCategory: 'cooked_meals',
      urgencyLevel: 'high',
      estimatedShelfLifeHours: 5,
      storageRecommendation: 'Refrigerate at 4°C or keep heated at 60°C+',
      confidenceScore: 96,
      explanation: 'Chicken-based dish with rice. High protein content, must be consumed within 6 hours of preparation.',
      safetyWarnings: ['Contains poultry - temperature control critical', 'Reheat thoroughly before serving'],
    },
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(0.5),
  },
  {
    id: 'donation-5',
    donorId: 'user-donor-2',
    donorName: 'Vikram Nair',
    donorOrgName: 'Fresh Harvest Market',
    foodName: 'Full-Fat Milk & Yogurt',
    category: 'dairy',
    quantity: 40,
    quantityKg: 20,
    preparationTime: hoursAgo(4),
    expiryTime: hoursFromNow(10),
    storageCondition: 'refrigerated',
    pickupAddress: 'Karol Bagh, New Delhi',
    location: { lat: 28.6280, lng: 77.2190, address: 'Karol Bagh, New Delhi' },
    notes: 'Near expiry date milk (500ml packs x 30) and fresh yogurt containers.',
    status: 'pending',
    urgencyLevel: 'high',
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(2),
  },
  {
    id: 'donation-6',
    donorId: 'user-donor-3',
    donorName: 'Sunita Mehta',
    donorOrgName: 'Olive Tree Bakery',
    foodName: 'Whole Wheat Bread Loaves',
    category: 'bakery',
    quantity: 45,
    quantityKg: 22,
    preparationTime: hoursAgo(8),
    expiryTime: hoursFromNow(40),
    storageCondition: 'ambient',
    pickupAddress: 'Lajpat Nagar, New Delhi',
    location: { lat: 28.5921, lng: 77.2289, address: 'Lajpat Nagar, New Delhi' },
    status: 'delivered',
    urgencyLevel: 'low',
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(2),
  },
  {
    id: 'donation-7',
    donorId: 'user-donor-1',
    donorName: 'Raj Kumar',
    donorOrgName: 'Grand Hyatt Restaurant',
    foodName: 'Paneer Butter Masala & Naan',
    category: 'cooked_meals',
    quantity: 65,
    quantityKg: 32,
    preparationTime: hoursAgo(3),
    expiryTime: hoursFromNow(3),
    storageCondition: 'heated',
    pickupAddress: 'Connaught Place, New Delhi',
    location: { lat: 28.6139, lng: 77.2090, address: 'Connaught Place, New Delhi' },
    notes: 'Vegetarian dish from today\'s lunch service.',
    status: 'picked_up',
    urgencyLevel: 'critical',
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'donation-8',
    donorId: 'user-donor-4',
    donorName: 'Nisha Agarwal',
    donorOrgName: 'The Taj Mahal Hotel',
    foodName: 'Assorted Pastries & Cakes',
    category: 'bakery',
    quantity: 90,
    quantityKg: 27,
    preparationTime: hoursAgo(5),
    expiryTime: hoursFromNow(20),
    storageCondition: 'refrigerated',
    pickupAddress: 'Diplomatic Enclave, New Delhi',
    location: { lat: 28.6448, lng: 77.1074, address: 'Diplomatic Enclave, New Delhi' },
    status: 'pending',
    urgencyLevel: 'medium',
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'donation-9',
    donorId: 'user-donor-2',
    donorName: 'Vikram Nair',
    donorOrgName: 'Fresh Harvest Market',
    foodName: 'Canned Lentils & Chickpeas',
    category: 'packaged_goods',
    quantity: 200,
    quantityKg: 80,
    preparationTime: hoursAgo(24),
    expiryTime: hoursFromNow(720),
    storageCondition: 'ambient',
    pickupAddress: 'Karol Bagh, New Delhi',
    location: { lat: 28.6280, lng: 77.2190, address: 'Karol Bagh, New Delhi' },
    notes: 'Slow-moving inventory. Best before 2 months away.',
    status: 'matched',
    urgencyLevel: 'low',
    createdAt: hoursAgo(24),
    updatedAt: hoursAgo(12),
  },
  {
    id: 'donation-10',
    donorId: 'user-donor-1',
    donorName: 'Raj Kumar',
    donorOrgName: 'Grand Hyatt Restaurant',
    foodName: 'Vegetable Biryani',
    category: 'cooked_meals',
    quantity: 55,
    quantityKg: 27,
    preparationTime: hoursAgo(1.5),
    expiryTime: hoursFromNow(4.5),
    storageCondition: 'heated',
    pickupAddress: 'Connaught Place, New Delhi',
    location: { lat: 28.6139, lng: 77.2090, address: 'Connaught Place, New Delhi' },
    status: 'delivered',
    urgencyLevel: 'high',
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'donation-11',
    donorId: 'user-donor-3',
    donorName: 'Sunita Mehta',
    donorOrgName: 'Olive Tree Bakery',
    foodName: 'Muffins & Cookies',
    category: 'snacks',
    quantity: 150,
    quantityKg: 18,
    preparationTime: hoursAgo(4),
    expiryTime: hoursFromNow(24),
    storageCondition: 'ambient',
    pickupAddress: 'Lajpat Nagar, New Delhi',
    location: { lat: 28.5921, lng: 77.2289, address: 'Lajpat Nagar, New Delhi' },
    status: 'pending',
    urgencyLevel: 'medium',
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'donation-12',
    donorId: 'user-donor-4',
    donorName: 'Nisha Agarwal',
    donorOrgName: 'The Taj Mahal Hotel',
    foodName: 'Fruit Juices & Soft Drinks',
    category: 'beverages',
    quantity: 100,
    quantityKg: 50,
    preparationTime: hoursAgo(2),
    expiryTime: hoursFromNow(48),
    storageCondition: 'refrigerated',
    pickupAddress: 'Diplomatic Enclave, New Delhi',
    location: { lat: 28.6448, lng: 77.1074, address: 'Diplomatic Enclave, New Delhi' },
    status: 'pending',
    urgencyLevel: 'low',
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
];

export const DEMO_REQUIREMENTS: FoodRequirement[] = [
  {
    id: 'req-1',
    ngoId: 'ngo-1',
    ngoName: 'Hope Food Bank',
    location: { lat: 28.6304, lng: 77.2177, address: 'Paharganj, New Delhi' },
    category: 'cooked_meals',
    quantityNeeded: 200,
    urgency: 'high',
    beneficiariesCount: 150,
    notes: 'Daily meal requirement for shelter residents',
    isActive: true,
    createdAt: hoursAgo(5),
  },
  {
    id: 'req-2',
    ngoId: 'ngo-2',
    ngoName: 'St. Jude Shelter Home',
    location: { lat: 28.6562, lng: 77.2410, address: 'Civil Lines, New Delhi' },
    category: 'cooked_meals',
    quantityNeeded: 150,
    urgency: 'critical',
    beneficiariesCount: 100,
    notes: 'Emergency meal requirement - kitchen under maintenance',
    isActive: true,
    createdAt: hoursAgo(2),
  },
  {
    id: 'req-3',
    ngoId: 'ngo-3',
    ngoName: 'City Community Kitchen',
    location: { lat: 28.5706, lng: 77.3210, address: 'Noida Sector 18, UP' },
    category: 'fresh_produce',
    quantityNeeded: 100,
    urgency: 'medium',
    beneficiariesCount: 300,
    notes: 'Vegetables for weekend cooking program',
    isActive: true,
    createdAt: hoursAgo(8),
  },
  {
    id: 'req-4',
    ngoId: 'ngo-4',
    ngoName: 'Child Care Trust',
    location: { lat: 28.5355, lng: 77.3910, address: 'Greater Noida, UP' },
    category: 'dairy',
    quantityNeeded: 80,
    urgency: 'medium',
    beneficiariesCount: 60,
    notes: 'Milk for children aged 2-10',
    isActive: true,
    createdAt: hoursAgo(6),
  },
  {
    id: 'req-5',
    ngoId: 'ngo-5',
    ngoName: 'Grace Meal Program',
    location: { lat: 28.5245, lng: 77.1855, address: 'Vasant Kunj, New Delhi' },
    category: 'bakery',
    quantityNeeded: 120,
    urgency: 'low',
    beneficiariesCount: 80,
    notes: 'Bread for breakfast program',
    isActive: true,
    createdAt: hoursAgo(10),
  },
];

export const DEMO_DELIVERIES: DeliveryTask[] = [
  {
    id: 'delivery-1',
    donationId: 'donation-2',
    donationName: 'Assorted Croissants & Sourdough',
    matchId: 'match-1',
    volunteerId: 'volunteer-2',
    volunteerName: 'Meera Kapoor',
    donorName: 'Sunita Mehta',
    donorOrgName: 'Olive Tree Bakery',
    pickupLocation: { lat: 28.5921, lng: 77.2289, address: 'Lajpat Nagar, New Delhi' },
    dropoffLocation: { lat: 28.5245, lng: 77.1855, address: 'Vasant Kunj, New Delhi' },
    ngoName: 'Grace Meal Program',
    status: 'accepted',
    distanceKm: 7.2,
    estimatedMinutes: 25,
    quantity: 120,
    quantityKg: 36,
    category: 'bakery',
    urgencyLevel: 'medium',
    acceptedAt: hoursAgo(1),
    createdAt: hoursAgo(2),
  },
  {
    id: 'delivery-2',
    donationId: 'donation-7',
    donationName: 'Paneer Butter Masala & Naan',
    matchId: 'match-2',
    volunteerId: 'user-volunteer-1',
    volunteerName: 'Arjun Singh',
    donorName: 'Raj Kumar',
    donorOrgName: 'Grand Hyatt Restaurant',
    pickupLocation: { lat: 28.6139, lng: 77.2090, address: 'Connaught Place, New Delhi' },
    dropoffLocation: { lat: 28.6304, lng: 77.2177, address: 'Paharganj, New Delhi' },
    ngoName: 'Hope Food Bank',
    status: 'picked_up',
    distanceKm: 3.1,
    estimatedMinutes: 12,
    quantity: 65,
    quantityKg: 32,
    category: 'cooked_meals',
    urgencyLevel: 'critical',
    acceptedAt: hoursAgo(2),
    pickedUpAt: hoursAgo(1),
    createdAt: hoursAgo(3),
  },
  {
    id: 'delivery-3',
    donationId: 'donation-6',
    donationName: 'Whole Wheat Bread Loaves',
    matchId: 'match-3',
    volunteerId: 'volunteer-4',
    volunteerName: 'Sunita Devi',
    donorName: 'Sunita Mehta',
    donorOrgName: 'Olive Tree Bakery',
    pickupLocation: { lat: 28.5921, lng: 77.2289, address: 'Lajpat Nagar, New Delhi' },
    dropoffLocation: { lat: 28.5706, lng: 77.3210, address: 'Noida Sector 18, UP' },
    ngoName: 'City Community Kitchen',
    status: 'delivered',
    distanceKm: 12.4,
    estimatedMinutes: 35,
    quantity: 45,
    quantityKg: 22,
    category: 'bakery',
    urgencyLevel: 'low',
    acceptedAt: hoursAgo(9),
    pickedUpAt: hoursAgo(8),
    deliveredAt: hoursAgo(7),
    createdAt: hoursAgo(10),
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-donor-1',
    title: 'Donation Matched! 🎉',
    message: 'Your Dal Makhani donation has been matched with Hope Food Bank.',
    type: 'match',
    isRead: false,
    createdAt: hoursAgo(1),
  },
  {
    id: 'notif-2',
    userId: 'user-ngo-1',
    title: 'New Donation Available',
    message: 'A new cooked meal donation (50 meals) is available nearby - 2.3 km away.',
    type: 'info',
    isRead: false,
    createdAt: hoursAgo(0.5),
  },
  {
    id: 'notif-3',
    userId: 'user-volunteer-1',
    title: 'Delivery Completed! ⭐',
    message: 'You successfully delivered Paneer Butter Masala to Hope Food Bank. Thank you!',
    type: 'delivered',
    isRead: true,
    createdAt: hoursAgo(1),
  },
  {
    id: 'notif-4',
    userId: 'user-donor-1',
    title: '⚠️ Expiry Warning',
    message: 'Your donation "Dal Makhani & Rice Combo" expires in less than 4 hours!',
    type: 'expiry',
    isRead: false,
    createdAt: hoursAgo(0.25),
  },
];

export const DEMO_IMPACT: ImpactMetrics = {
  totalMeals: 3640,
  totalKgRescued: 1820,
  co2SavedKg: 4550,
  landfillDivertedKg: 1820,
  totalDeliveries: 142,
  beneficiariesServed: 2180,
  activeDonations: 8,
  expiredDonations: 12,
};
